apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: bookstore-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Minikube 单节点足够；生产环境建议 10Gi+
  storageClassName: standard  # Minikube 默认 StorageClass